name: RunTests
run-name: ğŸ‰ Your First Binary PS Module! ğŸ‰
on: [
  push,
  pull_request
]
defaults:
  run:
    shell: pwsh
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§ª Pester Tests
        id: test
        run: |
          Write-Host -Fore Green "Running Available Tests in $PWD"
          Import-Module Pester -PassThru
          Invoke-Pester tests/Example.1.Tests.ps1